// enum - enumeration
export enum MatchCategory {
  UiGraphics = "UI Graphics",
  Fonts = "Fonts",
  Colors = "Colors",
  Icons = "Icons",
  Logos = "Logos",
  Favicons = "Favicons",
  IconFonts = "Icon Fonts",
  StockPhotos = "Stock Photos",
  StockVideos = "Stock Videos",
  StockMusicSoundEffects = "Stock Music & Sound Effects",
  VectorsClipArt = "Vectors & Clip Art",
  ProductImageMockups = "Product & Image Mockups",
  HTMLCSSTemplates = "HTML & CSS Templates",
  CSSFrameworks = "CSS Frameworks",
  CSSMethodologies = "CSS Methodologies",
  CSSAnimations = "CSS Animations",
  JavascriptAnimationLibraries = "Javascript Animation Libraries",
  JavascriptChartLibraries = "Javascript Chart Libraries",
  UIComponentsKits = "UI Components & Kits",
  ReactUILibraries = "React UI Libraries",
  VueUILibraries = "Vue UI Libraries",
  AngularUILibraries = "Angular UI Libraries",
  SvelteUILibraries = "Svelte UI Libraries",
  ReactNativeUILibraries = "React Native UI Libraries",
  DesignSystemsStyleGuides = "Design Systems & Style Guides",
  OnlineDesignTools = "Online Design Tools",
  DownloadableDesignSoftware = "Downloadable Design Software",
  DesignInspiration = "Design Inspiration",
  ImageCompression = "Image Compression",
  ChromeExtensions = "Chrome Extensions",
  Others = "Others",
}
